[tool.poetry]
name = "shooty-game"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.0.2"
gym = "^0.19.0"
stable-baselines3 = "^1.4.0"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pycodestyle = "^2.8.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
