name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run static code analysis
      run: |
        poetry run pylint **/*.py
    - name: Run type checker
      run: |
        poetry run pyre --strict check
    - name: Run tests
      run: |
        PYTHONPATH=. poetry run pytest
